name: test
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=7.3.0
  - jinja2
  - matplotlib
  - graphviz
  - bcftools =1.15
  - samtools =1.15.1
  - bwa =0.7.17
  - pysam =0.19.1
  - pygments
