name: test
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=7.25.0
  - jinja2
  - matplotlib
  - graphviz
  - bcftools =1.15
  - samtools =1.17
  - bwa =0.7.17
  - pysam =0.21.0
  - pygments
