name: Snakemake CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    

    - name: Install mambaforge on Linux
      run: curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh -o Mambaforge-Linux-x86_64.sh && bash Mambaforge-Linux-x86_64.sh
    
    - name: Install Conda environment from environment.yml
      uses: mamba-org/provision-with-micromamba@main

    - name: execute workflow
      run: snakemake --cores=1

    - name: mapped_reads
      uses: actions/upload-artifact@v3

      with:
        name: mapped_reads
        path: mapped_reads/
    
    - name: plots
      uses: actions/upload-artifact@v3

      with:
        name: plots
        path: plots/quals.svg

    - name: calls
      uses: actions/upload-artifact@v3

      with:
        name: cals
        path: calls/all.vcf